Already-12-O-clock/ABCDmoviE

README.md
이번 프로젝트에서 진행하였으면 하는 스킬 정보를 작성하였습니다.
=> [feat] README.md skills 제안

index.html
- 없음
- 없음
- index.html 파일 생성
- src 폴더 생성
- src/styles/style.css
- src/js/main.js
- 없음
- 없음
=> feat: 기본 디렉토리 설정

.gitignore, index.html, src/pages/mainPage.html, src/styles/reset.css
- src/styles/style.css
- index.html
- src/styles/reset.css
- .gitignore
- 페이지 생성 시 mainPage.html에 있는 기본설정을 재사용해주시길 바랍니다.
=> style: 공통 스타일 설정(reset.css)

.gitignore
- SERVICE_KEY.js 생성
- .gitignore에 해당 파일 추가하여 보안 사항 반영
- 없음
- .gitignore
- /src/service/SERVICE_KEY.js (.gitignore로 인해 반영되지 않음)
- .gitignore로 인해 git repository upload가 되지 않아 공유되지 못하고 있습니다.
- 추후 배포의 과정에서 해당 키에 대한 보안을 유지하면서 deploy 하는 방법을 알아봐야할 것 같습니다.
- 해당 파일의 내용은 개별적으로 안내드리겠습니다.
=> feat: KMDB, KOBIS service 키 관리

minutes/conventions/git_commit.md
- 없음
- 없음
- minutes/conventions/git_commit.md
- git commit message 작성 세부 안내를 참고하세요.
- git commit message에서 footer 부분의 작성을 선택사항으로 남기는 것이 좋을 듯합니다. 즉, code 변경사항을 기록하기 위해 직접 복사 붙여넣기를 할 때에만 사용하는 것이 좋을 것 같습니다.
- 없음
=> docs: git commit 컨벤션

index.html, src/pages/mainPage.html
- 없음
- index.html
- 없음
- 없음
- font-awesome 버전 5.15.4를 적용함
- 지원되는 버전의 것이 아닌 경우에는 미적용됨에 유의
- 무료로 제공되는 것이 아닌 경우에는 미적용됨에 유의
=> style: index.html과 mainPage.html에 font-awesome 적용

src/pages/mainPage.html
- 없음
- 없음
- 없음
- .tit-btn-wrap div 요소 안의 a 요소에 .login-btn 클래스명 추가
=> fix: mainPage.html 로그인 a 요소 클래스명 추가

src/pages/selectTheaterPage.html
- 없음
- src/pages/selectTheaterPage.html
- 없음
- 없음
- .tit-btn-wrap div 요소 안의 a 요소에 .login-btn 클래스명 추가
=> fix: selectTheaterPage.html 로그인 a 요소 클래스명 추가

.gitignore, package-lock.json, package.json
- 없음
- .gitignore
- .env
- requestAPI.js
- package.json
- package-lock.json
- 없음
- .env 파일을 캡쳐하여 이미지 파일로 보내드리겠습니다.
- ※ 주의 ※ 아래의 작업은 다음 스텝들을 거쳐 진행하여 주시기 바랍니다.
1. 이 PR 내용이 Merge가 된 다음에 진행합니다
2. 개인별 GitHub의 ABCDmoviE 레포지토리 안에서  fork sync를 맞춥니다.
3. 로컬 환경의 vscode에서 main 브랜치로 전환되어 있음을 확인합니다.
4. git pull 하여 변경 사항을 로컬 환경으로 모두 받아옵니다.
5. index.html과 동일한 폴더트리 레벨에서 .env 파일을 생성 및 전달사항을 입력한 뒤 저장해줍니다.
6. .gitignore에 ".env" 파일명이 존재하는지 다시 한번 확인합니다.
- 해당 파일은 git과 무관하오니 로컬 환경에서 vscode로 main 브랜치 안에서 직접 파일을 생성하여 사용하시면 됩니다.
- 로컬 환경에 package.json, package-lock.json 파일이 추가되어 있는 상태에서 터미널(.zsh 또는 bash) 안에 다음을 입력하여 모듈 설치를 진행합니다.
```
npm install
```
=> setting: npm 개발 환경 설정- Package.json, Package-lock.json, .env, .gitignore, requestAPI.js

minutes/11.18/Readme.md
- 없음
- 없음
- minutes/11.18/Readme.md
- 없음
- 프로젝트 방향논의
- api 활용
- commit & branch 시점
- style 폴더구조
-  트러블슈팅 작성
=> docs: 11월 18일 회의록

package.json
- 없음
- package.json
- 없음
- 없음
- "type": "module"로 진행합니다.
- (참고자료) [CommonJS vs ES6](https://code-designer.tistory.com/103#:~:text=CommonJS%20%EC%99%80%20ES6%20%EB%8A%94%20%EA%B7%BC%EB%B3%B8%EC%A0%81,%EC%9D%98%20%EC%B0%A8%EC%9D%B4%EC%A0%90%20%EC%9D%B5%ED%98%80%EB%86%93%EC%9D%84%20%EA%B2%83.)
- ((참고자료) [import와 require 차이](https://inpa.tistory.com/entry/NODE-%F0%9F%93%9A-require-%E2%9A%94%EF%B8%8F-import-CommonJs%EC%99%80-ES6-%EC%B0%A8%EC%9D%B4-1)
=> setting: package.json type 설정

index.html, src/styles/index.css
없음
- index.html
- src/styles/index.css
- 페이지의 첫 시작화면이라 영화 포스터 외에 캐치프레이즈나 사이트를 소개하는 문장이 간단하게 한 줄 있으면 어떨까 생각했습니다.
- JavaScript 작업 전이므로 이미지 없이 border로 형태가 보이게 작업했습니다.
- 제공된 피그마의 캐러셀 이미지를 기반으로 작업했습니다. 버튼 텍스트 내용이나 위치 등 임의로 작업한 부분이 있기 때문에 관련해서도 피드백 편하게 주시면 감사드리겠습니다!
=> style: index 페이지 마크업과 스타일링

src/pages/loginPage.html, src/styles/components/login.css
- 없음
- src/pages/loginPage.html 전체 작성
- src/components/login.css 전체 작성 이동
- src/pages/loginPage.html 전체 작성
- src/components/login.css 전체 작성 이동
- 없음
해당 html, css 중 조금 수정을 요하는 것이 보이면 적극적인 피드백 부탁드립니다
추가과제인 ID찾기 / 비밀번호 찾기 / 회원가입 등은 프로젝트 속도에 따라 진행 여부를 결정하려고 합니다
- 미리보기 화면
=> feat: 로그인 페이지 구현

package-lock.json, package.json
find-config 모듈 추가
- 없음
- package.json
- package-lock.json
- 없음
- 없음
- 파일의 경로를 찾는 모듈
- .env 파일의 경로를 찾기 위해 설치함
=> setting: package.json_and_package-lock.json/find-config 모듈 추가

requestAPI.js
- 없음
- requestAPI.js
- 없음
- 없음
- createDB 함수는 다음과 같이 동작합니다.
- 검색 조건이 담긴 쿼리object를 인자로 받음
- id와 key를 인자로 받아 접근권한(Authorization) 확인
- 받아온 데이터를 db 폴더 안의 naverDB.json 파일에 저장
- 기존 naverDB.json이 있는 경우 기존 파일을 삭제하고 새로 받은 데이터로 naverDB.json을 업데이트
=> feat: requestAPI.js/createDB 함수 생성

.gitignore, src/js/test.js, src/pages/test.html
- 없음
- .gitignore
- src/pages/test.html
- src/js/test.js
- naverDB.json 파일은 매 요청시마다 갱신됩니다. 따라서 git repository에 저장할 필요가 없다고 판단하였습니다. 또한, item의 갯수가 많을 경우를 대비하여 json 파일을 올리지 않았습니다. 하지만, 올리는 것이 더 좋을지 여부에 대한 의논이 필요해보입니다.
- test.js과 test.html 파일을 확인하시어 naverDB.json 파일이 잘 생성되는지 확인하여 주시기 바랍니다.
- naverDB 자료는 응답 받는 데이터의 특징 상 영화 메인페이지를 구현할 때 사용하기 적합하다고 볼 수 있으나, 영화 상세페이지, 캐러셀 페이지에는 부적합하다고 판단됩니다.  이에 대한 의논이 필요하다고 여겨집니다.
- test.html과 test.js에서 살펴보신 바와 같이 데이터를 요청 및 웹페이지 제작에 사용하시면 됩니다. 
- test.html과 test.js는 간단한 예제 파일입니다.
=> feat: naver openAPI를 통한 데이터 요청 방법 및 간단한 바닐라JS SPA 페이지 구현

.gitignore, db/box_office_db.json
- 없음
- .gitignore
- db/box_office_db.json
- 없음
- 네이버 openAPI 호출 결과를 바탕으로 FAKE BOX OFFICE 10위권 데이터를 생성하였음
- index.html과 mainPage.html 데이터를 구현에 사용될 예정임
=> feat: db/box_office_db.json 생성

index.html, src/js/index.js, src/js/test.js, src/pages/test.html, src/styles/index.css
- 없음
- index.html
- src/js/test.js
- src/pages/test.html
- src/styles/index.css
- 없음
- naver에서 데이터를 가져와 페이크 박스오피스 DB를 구성하였습니다.
- 해당 데이터는 box_office_db.json 파일에 있습니다.
- 데이터를 가져와 image와 title 정보를 필터링 하였습니다.
- 필터링된 데이터를 이용하여 img 요소를 생성하였습니다.
- index.css의 .item-list li 요소 스타일을 border 제거하고 overflow: hidden을 추가하였습니다.
=> feat: 캐러셀 페이지 기능 구현

README.md
#(이슈번호)
- 없음
- README.md
- 없음
- style 제거 => chore 추가
- design 추가
- 없음
close: #(이슈번호)
=> docs: 커밋 메시지 타입 변경

src/js/index.js
=> chore: index.js 불필요한 코드 주석 제거

src/js/index.js, src/js/main.js, src/pages/mainPage.html
#56 
- 없음
- src/js/index.js => rebase 과정에서 추가됨
- src/js/main.js
- 없음
close: #56
=> feat: box_office_db.json 데이터 요청 및 타이틀 정보 필터 함수 적용

src/pages/mainPage.html, src/pages/ticketingPage.html
#66
- 없음
- src/pages/ticketingPage.html
- 없음
close: #66
=> fix: header nav 메뉴 a요소 페이지 링크 연결 및 상영관 선택 article 이미지 url 설정

src/js/theaterSelect.js
#67
- 없음
- 없음
-  src/js/theaterSelect.js
close: #67
=> feat: 빠른 예매 페이지 내 상영관 선택 article 드롭다운 기능 구현

src/styles/ticketingPage.css
#70
- 없음
- src/styles/ticketingPage.css
- 없음
close: #70
=> design: 빠른 예매 페이지 progress-list li요소 cursor:pointer 적용

src/styles/components/login.css
#72
- 없음
- src/styles/components/login.css
- 없음
close: #72
=> design: 로그인 페이지 로그인 박스의 브라우저 내 위치 조정을 위해 margin 조정

src/js/ticketingPageOverall.js
#74
- 없음
- src/js/ticketingPageOverall.js
- 없음
close: #74
=> feat: progress 메뉴 버튼 디자인 및 활성화 기능 구현

src/js/getMovieData.js
#76
- 없음
- 없음
- src/js/getMovieData.js
- fetchAPI로 데이터 요청시 getMovieData.js의 MovieData 클래스를 사용하여 주세요~
close: #76
=> feat: fetchAPI 데이터 요청 MovieData 클래스로 분리 및 정규표현식 메서드 추가

src/js/index.js
=> feat: MovieData 클래스를 이용하여 데이터 요청하도록 변경

src/js/index.js
=> chore: index.js filterTitleReg 정규표현식 오타 수정

src/js/main.js
#82
- 없음
- src/js/main.js
- 없음
close: #82
=> feat: main.js에서 데이터 요청 MovieData 클래스 이용

index.html, src/pages/mainPage.html
#84
- 없음
- index.html
- 없음
close: #84
=> fix: index.html, mainPage.html 문서 script type을 module로 변경

src/js/movieSelect.js, src/pages/ticketingPage.html
#87
- 없음
- src/pages/ticketingPage.html
- src/js/movieSelect.js
close: #87
=> feat: 영화 선택 기능 구현

src/js/main.js, src/styles/components/main.css, src/styles/ticketingPage.css
#89 
- 없음
- src/js/main.js
- src/styles/components/main.css
- src/styles/ticketingPage.css
- 없음
close: #89
=> design: ticketingPage 영화선택 article 스타일 수정

src/js/ticketingPageOverall.js
#91
- 없음
- src/js/ticketingPageOverall.js
- 없음
close: #91
=> chore: 불필요한 주석 코드 제거

README.md
#
- 없음
- README.md
- 없음
close: #이슈번호
=> docs: README 빠른 예매 페이지 > 영화 선택 미리보기 이미지 추가

src/js/index.js
#98 
- 없음
- 없음
- 없음
- 산발적으로 API 데이터 요청과 관련하여 오류가 발생하고 있습니다.
- 이로 인하여 index.html에서 이미지 데이터를 정상적으로 받아오지 못하는 경우를 확인하였습니다.
- 이를 해결하기 위하여 class로 fetch를 요청 메서드를 이용하지 않고 index.js에서 직접 fetchAPI를 요청하여 테스트할 예정입니다.
close: #98
=> bug: index.js에서의 fetch 진행
